externalSecret:
  labels:
    fleetRelease: default
    addonsRelease: default
    monitoringRelease: default
    enable_metrics_server: "true"
    enable_external_secrets: "true"
    enable_aws_efs_csi_driver: "true"
    enable_external_dns: "true"
    enable_ack_iam: "true"
    enable_ack_eks: "true"
    # No need to specify tenant here as it will use the folder structure